# Default Opsimate Configuration
# This configuration is built into the Docker image and used when no custom config is provided

# Server configuration
server:
  port: 3001
  host: "0.0.0.0"  # Bind to all interfaces in container

# Database configuration
database:
  path: "/app/data/database/opsimate.db"  # Container path

# Security configuration
security:
  private_keys_path: "/app/data/private-keys"  # Container path for SSH keys

# mailer configuration
# Email functionality is disabled by default for security
# To enable email features:
# 1. Set enabled: true
# 2. Configure valid SMTP credentials below
# 3. Update mailLinkBaseUrl to your actual domain
mailer:
  enabled: false
  default_encoding: "UTF-8"
  host: "smtp.gmail.com"  # Replace with your SMTP server
  port: 587                
  secure: false
  mailLinkBaseUrl: "http://localhost:8080" # Replace with your actual domain
  from: "no-reply@yourdomain.com"  # Replace with your email
  replyTo: "ops@yourdomain.com"    # Replace with your support email
  auth:
    user: "your-email@domain.com"  # Replace with your SMTP username
    pass: "your-smtp-password"     # Replace with your SMTP password
  tls:
    rejectUnauthorized: true
